version: '3.7'

services:
  app:
    image: wingky/php8.1
    container_name: app
    hostname: app
    restart: unless-stopped
    ports:
      - "8090:80"
    networks:
      - internal
    volumes:
      - app_test:/var/www/html
volumes:
  app:

networks:
  internal:
